language: ruby
rvm:
  #- ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7

cache: bundler

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - gem install bundler
