language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
notifications:
  irc: "irc.freenode.org#cells"
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails3-0
  - gemfiles/Gemfile.rails3-1
  - gemfiles/Gemfile.rails3-2
