language: ruby
rvm:
  #- ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

cache: bundler

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  # Apply workaround from https://github.com/colszowka/simplecov/commit/ba423820d1d1164fcc038e7b6163b8a96d1786be
  # if `gem update --system` fail (Ruby < 2.3)
  - gem update --system || gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler || gem install bundler -v '1.17.3'
